// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLIntro_MLApp
{
    public partial class MLIntro
    {
        /// <summary>
        /// model input class for MLIntro.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"longitude")]
            public float Longitude { get; set; }

            [ColumnName(@"latitude")]
            public float Latitude { get; set; }

            [ColumnName(@"housing_median_age")]
            public float Housing_median_age { get; set; }

            [ColumnName(@"total_rooms")]
            public float Total_rooms { get; set; }

            [ColumnName(@"total_bedrooms")]
            public float Total_bedrooms { get; set; }

            [ColumnName(@"population")]
            public float Population { get; set; }

            [ColumnName(@"households")]
            public float Households { get; set; }

            [ColumnName(@"median_income")]
            public float Median_income { get; set; }

            [ColumnName(@"median_house_value")]
            public float Median_house_value { get; set; }

            [ColumnName(@"ocean_proximity")]
            public string Ocean_proximity { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLIntro.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLIntro.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
